sudo: required
language: python
python:
    - 3.8

script:
    - export PYTHONPATH="$(pwd)"
    - pip install codecov
    - cd test
    - coverage run -m unittest discover -v --pattern=*.py

after_success:
- codecov

notifications:
  email: false
